AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/dartsass.rb'

Metrics/AbcSize:
  Exclude:
    - 'engines/af_core/app/services/af_core/cache_manager.rb'

Metrics/BlockLength:
  Exclude:
    - 'engines/**/*_spec.rb'

Style/OpenStructUse:
  Exclude:
    - 'engines/**/*_spec.rb'

Lint/MissingSuper:
  Exclude:
    - 'engines/af_core/app/models/af_core/timeline.rb'
