services:
  postgres:
    container_name: appleforecast_postgres
    image: postgres
    restart: always
    shm_size: 128mb # set shared memory limit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  redis:
    container_name: appleforecast_redis
      # command: redis-server --requirepass password
    image: "redis:7-alpine"
    ports:
      - 6379:6379

  adminer:
    container_name: appleforecast_dbadmin
    image: adminer
    restart: always
    ports:
      - 8080:8080