default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
  host: localhost

development:
  <<: *default
  database: af_development
  user: postgres
  password: postgres

test:
  <<: *default
  database: af_test
  user: postgres
  password: postgres
